### ISSUE TITLE
Request is not send.

### ISSUE THREAD

**Issue by fcpauldiaz** [tehplague/swiftmailer-mailgun-bundle#31]
I don't know why this bundle stopped working. I don't know what changes I have to make for mailgun 2.0. I'm not receiving any log error, the emails are just not send.

I'm using the dev-master branch and 
this dependencies`

        "php": "^5.5|^7.0",
        "guzzlehttp/psr7": "~1.2",
        "php-http/httplug": "^1.0",
        "php-http/discovery": "^0.8"
`
Do I have to update the dependencies?

Edit: I downgraded to v0.2.1 and it worked
```yaml
cspoo_swiftmailer_mailgun:
    key: "%api_email_key%"
    domain: "mailgun.newtonlabs.com.gt"

# Swiftmailer Configuration
swiftmailer:
    transport: "mailgun"
    spool:     { type: memory }

**Comment by Nyholm** [comment]
Since 0.3.1 we depend on Mailgun 2.x. They have updated their dependencies quite a lot. 
Last night Mailgun 2.1 was released which makes things a bit easier. 

You should make sure to install `php-http/discovery:^1.0`, `php-http/guzzle6-adapter` and `php-http/message`. The API is the same if you are using Mailgun via this bundle. 

If it does not work for you. Please get back with some log messages or something. The above was just guesses. =)

**Comment by fcpauldiaz** [comment]
I was missing the php-http/guzzle6-adapter dependency. Good guess, thanks.
