### ISSUE TITLE
Implement detailed logging for Mailgun exceptions

### ISSUE THREAD

**Issue by richard-keller** [tehplague/swiftmailer-mailgun-bundle#34]
As far as I can tell, currently we are limited to the `Swift_Events_SendEvent` error codes. This means that when Mailgun throws an error, we don't have any indication of what the underlying cause of the underlying error is.

This was a problem for us recently, where we would randomly get sporadic mail delivery failures, but with no way to tell what was causing them since we didn't have access to the Mailgun API response code.

Would you consider an option to allow more detailed logging, specifically the exception message that Mailgun throws when it encounters an error? This should be as simple as a config option for enabling detailed logging, and then injecting the logger service into `MailgunTransport`.

**Comment by Nyholm** [comment]
Enabling more logging sounds like a great idea. I would be happy to review such PR.

**Comment by levijackson** [comment]
I am looking for something similar. Any thoughts on bubbling the exception up? It could cause breakage if this is silently failing for anyone right now.

```
try {
            $this->mailgun->messages()->sendMime($domain, $postData['to'], $message->toString(), $postData);
            $resultStatus = Swift_Events_SendEvent::RESULT_SUCCESS;
        } catch (\Exception $e) {
            $failedRecipients = $postData['to'];
            $sent = 0;
            $resultStatus = Swift_Events_SendEvent::RESULT_FAILED;

            $swiftException = new Swift_TransportException($e->getMessage(), $e->getCode(), $e);
            if ($exceptionEvt = $this->eventDispatcher->createTransportExceptionEvent($this, $swiftException)) {
                $this->eventDispatcher->dispatchEvent($exceptionEvt, 'exceptionThrown');
                if ($evt->bubbleCancelled()) {
                    return 0;
                }
            }
        }
```

If the log is the better approach, we could tap into the `transportStopped` event so that the LoggerPlugin can be used. I'm not using this in a Symfony app, so I may need some guidance on the config portion.

**Comment by levijackson** [comment]
Ah, forget I said anything about throwing an exception. I was thinking about it more and what I proposed negates the original try/catch. I'm going to go down the route of implementing additional logging.

**Comment by 4c0n** [comment]
This issue has been open for a long time, here is my suggestion for adding logging to the package:
https://github.com/tehplague/swiftmailer-mailgun-bundle/pull/80

Please share your thoughts :)

**Comment by alister** [comment]
A paragraph in the README.md file saying that this feature is here, and how to enable it would be useful. I expect it's a few lines in the monolog configuration, but it would be good to have it confirmed with example code.

You might also rebase and/or squash some of the commits together to avoid the mid-commit-stream 'revert' and have the commits look better.

**Comment by 4c0n** [comment]
@alister Thanks for your feedback. Regarding squashing, the development might not be done yet, best way to avoid the problem you described is to use squash merging, IMO: https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests

As it would be something you want to do right before merging, otherwise you would have repeat yourself en constantly squash the commits.

As for adding information to the README file, I'd love to and will do that, as soon as the code is reviewed and we reached consensus about the way it should work. Otherwise if the plan changes 180 degrees into the other direction, we' d be wasting time. Also the configuration is not done using the monolog configuration, but by injecting a logger object, instead of the `NullLogger` from the PSR package, so it would likely be done using the service definitions, as mentioned in the PR description.

Does anyone here know the maintainer? He's not very responsive it seems.

**Comment by alister** [comment]
I was thinking more about [git rebase -i]( https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#squash-commits-together) to clean up the commits already there ahead of merging it.

As far as how it would be used - to use your own logger, you would alias the @logger (@monolog.logger, or another one you created) to `mailgun.logger` and so overriding the NullLogger in the config?

**Comment by 4c0n** [comment]
@alister Yes that's it :)

**Comment by 4c0n** [comment]
This issue can be closed as https://github.com/tehplague/swiftmailer-mailgun-bundle/pull/80 was merged. It is now possible to log api errors by overriding the `mailgun.logger` service with a logger that implements the PSR-3 `LoggerInterface`.

**Comment by Nyholm** [comment]
WohoO!
